# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-18 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('car_make', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_city', models.CharField(max_length=200)),
                ('arrival_city', models.CharField(max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Driver')),
            ],
        ),
    ]
