# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_year',
            field=models.IntegerField(max_length=10),
        ),
    ]
