# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160618_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_year',
            field=models.IntegerField(),
        ),
    ]
