# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160618_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
