# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160619_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
