# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_trip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_picture',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
