# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160618150656 on 2016-06-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20160619_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
